version: '3.4'

services:
  catalogdb:
   container_name: catalogdb
   restart: always
   volumes: 
   - C:\Users\anirudh.singh.bharti\OneDrive - Accenture\Desktop\mongo:/data/db
   ports:
   - "27017:27017"

  basketdb:
   container_name: basketdb
   restart: always    
   ports:
   - "6379:6379"
   
  catalog.api:
   container_name: catalogapi
   environment:
   - ASPNETCORE_ENVIRONMENT=Development
   depends_on:
   - catalogdb
   volumes:
   - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
   - ${HOME}/.aspnet/https:/root/.aspnet/https/
   ports:
   - "5000:80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - basketdb
    ports:
     - "5001:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro